[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_nlu"
version = "0.1.0"
description = "NLU core functionalities"
dependencies = ["numpy", "spacy", "transformers"]
